repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
    - id: flake8
      additional_dependencies:
          - flake8-blind-except
          - flake8-bugbear
          - flake8-builtins
          - flake8-commas
          - flake8-comprehensions
          - flake8-print

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: master
    hooks:
    - id: isort

  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    - id: yapf
      args: ["-i"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
    - id: check-ast
    - id: check-merge-conflict
    - id: check-json
    - id: check-symlinks
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
